### PR TITLE
fix missing images in export

### PR DESCRIPTION
**Pull request by dirkroorda**
See the comments in the code.

Test it before applying it, since I did not do any building-bundling whatsoever.

### CODE REVIEW

**Comment by evolve2k** [comment]
Fix looks sensible to me.

@OliverBalfour could you look this over? It doesnt look like a very high risk change at all.

Image rendering images in the Obsidian Pandoc flow are affecting many people, this looks like it might solve a bunch of them.

People reporting (likley related) image exporting Issues:
https://github.com/OliverBalfour/obsidian-pandoc/issues/66
https://github.com/OliverBalfour/obsidian-pandoc/issues/81
https://github.com/OliverBalfour/obsidian-pandoc/issues/95
https://github.com/OliverBalfour/obsidian-pandoc/issues/118
https://github.com/OliverBalfour/obsidian-pandoc/issues/138

https://forum.obsidian.md/t/how-to-pass-image-directory-location-to-pandoc/33349
https://forum.obsidian.md/t/pandoc-does-not-show-embedded-images-in-docx/27209

**Comment by evolve2k** [comment]
@OliverBalfour I can see you've worked on this a bit as discussed in your [Future Directions](https://github.com/OliverBalfour/obsidian-pandoc/issues/139) post.

I reviwed your patch code, and this change is separate from what you've already done.

@dirkroorda dirkroorda thanks for this patch, could you clean up and remove all the comments except for the code change lines, that'll make it easier for someone to just hit MERGE.   I think here is the best place for disclaimers and workflow discussions, as you've done. Would be good to get this in if it's such a small simple fix and as you said it's working for you.

**Comment by dirkroorda** [comment]
@evolve2k Hi Richie, just did it.

**Comment by fuhadabdulla** [comment]
Looking forward to this update

**Comment by kw90** [comment]
Is there something missing here or could we merge this? This would improve my workflow a lot! Thanks for your work! 🙂

**Comment by evolve2k** [comment]
@OliverBalfour? Can you help us all out.

Hoping it's a very easy merge now. It's a 2 line change.

**Comment by Interpause** [comment]
It seems this patch only works for markdown mode, not html mode, referring to the below lines:

https://github.com/OliverBalfour/obsidian-pandoc/blob/68ff9e3733cc73055156455721fc736ad45c7d5e/main.ts#L106-L146

**Comment by EllriNidhogg** [comment]
So, the problem is pulling the path information from the file object when passing the .md file. It looks like the current code passes the raw HTML from stdin, which lacks path data. So a potential fix would be to generate a temporary HTML file in the directory of the input file, then remove it once the export is complete. It's kind of awkward but it solves the problem from the pandoc command line point of view?

**Comment by MavropaliasG** [comment]
Will this patch allow for images in PDF and odt too?

**Pull request closed without merging**
